# docker-compose.yml
# Front‑end (React + Nginx), Back‑end (Node/Express), MySQL 8.4

services:
  frontend:
    build: ./frontend           # Dockerfile lives in ./frontend
    image: p53-frontend:local
    container_name: p53-frontend
    ports:
      - "3001:80"               # <host>:<container>
    depends_on:
      - api                     # be sure API is up first

  api:
    build: ./api                # Dockerfile lives in ./api
    image: p53-api:local
    container_name: p53-api
    environment:
      DB_HOST: db               # use key‑value syntax (clearer)
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: p53-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql   # persist database files

volumes:
  dbdata:
